---
- name: "restart_ldap"
  ansible.builtin.service:
    name: "{{ ldap_service_name }}"
    state: restarted

- name: "restart_rsyslog"
  ansible.builtin.service:
    name: "rsyslog"
    state: restarted
